name: github follower purger

on:
  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
      - name: Purge followers
        run: |
          repo_owner=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.AUTH_TOKEN }}" https://api.github.com/user | jq -r ".login")
          for follower in $(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.AUTH_TOKEN }}" https://api.github.com/users/$repo_owner/followers | jq -r ".[].login"); do
            echo "purging $follower"
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TG_CHAT_ID }}" --data-urlencode "text=github-follower-purger: $follower"
            curl -s -X PUT -H "Authorization: token ${{ secrets.AUTH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/blocks/$follower
            curl -s -X DELETE -H "Authorization: token ${{ secrets.AUTH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/blocks/$follower
          done
