name: github follower purger

on:
  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Purge my github followers
        run: |
          owner=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.AUTH_TOKEN }}" https://api.github.com/user | jq -r ".login")
          for user in $(curl -s -X GET -H "Authorization: token ${{ secrets.AUTH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/blocks | jq -r ".[].login"); do
            echo "unblocking $user"
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TG_CHAT_ID }}" --data-urlencode "text=unblocking $user"
            curl -s -X DELETE -H "Authorization: token ${{ secrets.AUTH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/blocks/$user
          done
          for user in $(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.AUTH_TOKEN }}" https://api.github.com/users/$owner/followers | jq -r ".[].login"); do
            echo "blocking $user"
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TG_CHAT_ID }}" --data-urlencode "text=blocking $user"
            curl -s -X PUT -H "Authorization: token ${{ secrets.AUTH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/blocks/$user
          done
